version: '3'
services:
  electrumx:
    build: .
    image: bitcraftio/electrumx
    volumes:
        - "../env:/home/electrumx/scripts/electrumx/env"
    depends_on:
      - bitcoind
  bitcoind:
    image: bitcraftio/bitcoind
    command: ["bitcoind", "-rpcallowip=::/0", "-txindex=1", "-server", "-testnet"]
    volumes:
      - "../bitcoin-testnet-data:/bitcoin/.bitcoin"
